# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches:
      - master
      - release/*
      - hotfix/*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: cd client && yarn
    - name: Login to heroku container registry
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: heroku container:login  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "full-spec-devops-nodejs"
        heroku_email: "bitpocketer@gmail.com"
        usedocker: true
